//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleMVCTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESSION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SESSION()
        {
            this.EQUIPMENTS = new HashSet<EQUIPMENT>();
            this.STAFFS = new HashSet<STAFF>();
        }
    
        public decimal SESSION_CODE { get; set; }
        public System.DateTime START_TIME { get; set; }
        public decimal ACTIVITY_ID { get; set; }
        public decimal ROOM_ID { get; set; }
        public string REF_NO { get; set; }
    
        public virtual ACTIVITy ACTIVITy { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual ROOM ROOM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQUIPMENT> EQUIPMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STAFF> STAFFS { get; set; }
    }
}
